"""empty message

Revision ID: 97ae62677006
Revises: 
Create Date: 2025-12-30 17:25:29.376636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ae62677006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_image', sa.String(), nullable=False),
    sa.Column('country_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_name')
    )
    op.create_table('booking_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_image', sa.String(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_name')
    )
    op.create_table('booking_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_image', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['booking_country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_name')
    )
    op.create_table('booking_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('client', 'owner', name='rolechoices'), nullable=False),
    sa.Column('registered_date', sa.DateTime(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['booking_country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('booking_hotel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.Integer(), nullable=False),
    sa.Column('hotel_stars', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['booking_city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['booking_country.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['booking_profile.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['booking_service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['booking_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_hotel_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_image', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['booking_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_add', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['booking_hotel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['booking_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.Enum('Люкс', 'Полулюкс', 'Семейный', 'Эконом', 'Одноместный', name='roomtypechoices'), nullable=False),
    sa.Column('room_status', sa.Enum('Занят', 'Забронирован', 'Свабоден', name='roomstatuschoices'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['booking_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_room_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_image', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['booking_hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['booking_hotel.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['booking_room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['booking_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking_booking')
    op.drop_table('booking_room_image')
    op.drop_table('booking_room')
    op.drop_table('booking_review')
    op.drop_table('booking_hotel_image')
    op.drop_table('refresh_token')
    op.drop_table('booking_hotel')
    op.drop_table('booking_profile')
    op.drop_table('booking_city')
    op.drop_table('booking_service')
    op.drop_table('booking_country')
    # ### end Alembic commands ###
